name: 'SDK Generate'
description: 'SDK generation automation'
inputs:
  token:
    description: Personal access token
    required: false
    default: ${{ github.token }}
  app-name:
    description: Name of the application
    required: true
  swag-spec-location:
    description: Location where the Swagger spec should be saved to
    default: .schema/api.swagger.json
    required: false
  swag-spec-ignore:
    description: Packages to ignore when generating the Swagger spec (space delimited)
    default: "internal/httpclient"
    required: false
  swag-gen-path:
    description: Where to generate the SDK to
    default: "internal/httpclient"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        path: current-repo
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - run: |
        git config --global user.email "60093411+ory-bot@users.noreply.github.com"
        git config --global user.name "ory-bot"
      shell: bash
    - run: echo 'GOPATH='"$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash
    - run: |
        cd current-repo
        wget https://github.com/go-swagger/go-swagger/releases/latest/download/swagger_linux_amd64 \
          -O "$GOPATH/bin/swagger"
        chmod +x "$GOPATH/bin/swagger"
        bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b $GOPATH/bin ory
      shell: bash
    - env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        cd current-repo
        make sdk
      shell: bash
    - run: |
        cd current-repo
        echo "::set-output name=msg::$(git log --format=%B -n1)"
      id: commit-msg
      shell: bash
    - if: ${{ !startsWith(steps.commit-msg.outputs.msg, 'autogen') }}
      run: |
        cd current-repo
        git add -A
        git commit -a -m "autogen(openapi): regenerate swagger spec and internal client" || true
      shell: bash
    - if: ${{ github.ref_type == 'branch' }}
      run: |
        cd current-repo
        git pull --rebase origin "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
        git push origin HEAD:"${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" || true
      shell: bash
    - if: ${{ github.ref_type == 'tag' }}
      run: |
        cd current-repo
        git pull --rebase origin master || true
        git push origin HEAD:master || true
      shell: bash
