version: 2.1
description: Run gloangci tools

orbs:
  go: circleci/go@1.5.0

executors:
  default:
    docker:
      - image: cimg/go:1.16-node
        environment:
          GOPROXY: 'https://proxy.golang.org,direct'

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - v1-golangci-lint-1.46.2
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/.bin v1.46.2
      - save_cache:
          key: v1-golangci-lint-1.46.2
          paths:
            - ~/.bin
  lint:
    steps:
      - run: PATH=$HOME/.bin:$PATH GOGC=100 golangci-lint run --timeout 10m0s

jobs:
  lint:
    executor: default
    steps:
      - checkout
      - lint

examples:
  lint:
    description: Lint using golangci-lint
    usage:
      version: 2.1
      orbs:
        foo: ory/nancy@0.0.1
      workflows:
        lint:
          jobs:
            - run-linter:
                steps:
                  - checkout
                  - foo/lint
