version: 2.1
description: # The purpose of this orb

orbs:
  changelog:
    executors:
      changelog:
        docker:
          -
            image: circleci/ruby:2.5-node
    jobs:
      changelog:
        parameters:
          repo:
            description: The GitHub repository
            type: string
          org:
            description: The GitHub username
            type: string
          gitemail:
            description: The git committer's email
            type: string
            default: office+ci@ory.sh
          gitusername:
            description: The git committer's username
            type: string
            default: ORY Continuous Integration
          gitauthtoken:
            description: The git committer's username
            type: string
            default: ORY Continuous Integration
          gitauthuser:
            description: The git committer's username
            type: string
            default: ORY Continuous Integration
        executor: changelog
        steps:
          - checkout
          - run: gem install github_changelog_generator -v 1.14.3
          - run: sudo npm i -g doctoc
          - restore_cache:
              keys:
                - changelog-v1
          - run: github_changelog_generator -u <<parameters.org>> -p <<parameters.repo>> -o CHANGELOG.md --token $GITHUB_TOKEN --cache-file /tmp/github_changelog_generator
          - save_cache:
              key: changelog-v1
              paths:
                - "/tmp/github_changelog_generator"
          - run: doctoc CHANGELOG.md
          - run: git config --global user.email "<<parameters.gitemail>>"
          - run: git config --global user.name "<<parameters.default>>"
          - run: git add CHANGELOG.md
          - run: |
              git commit -m "Update CHANGELOG [ci skip]" -- CHANGELOG.md
          - run: git remote rm origin
          - run: git remote add origin https://<<parameters.gitauthtoken>>:<<parameters.gitauthtoken>>@github.com/<<parameters.org>>/<<parameters.repo>>.git
          - run: git push origin

workflows:
  changelog:
    jobs:
      - jobs/changelog
